# Mutable candidate for the MLX+BPE smoke example.
# Defaults favor portability; switch MLX_DEVICE to gpu on Apple Silicon for faster runs.

VOCAB_SIZE=320
MIN_PAIR_FREQUENCY=2
MAX_TRAINING_BYTES=20000

MLX_DEVICE=cpu
TIME_BUDGET=1
LEARNING_RATE=0.001
WEIGHT_DECAY=0.0

MAX_SEQ_LEN=32
DEVICE_BATCH_SIZE=1
TOTAL_BATCH_SIZE=32
EVAL_TOKENS=512

MLX_LAYERS=1
MLX_DIM=32
MLX_HEADS=4
MLX_MLP_DIM=64
MLX_WINDOW_PATTERN=L
